### PR TITLE
feat(wizards): update page appearance

### PR DESCRIPTION
**Pull request by andreybakanovsky**

### CODE REVIEW

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Review by VladislavSokov — APPROVED** [review]

**Comment by andreybakanovsky** [comment]
The appearance of images with the background image was improved by means of the last commit:
image

**Pull request merged**
