### PR TITLE
feat(accounts page): update design

### PR DESCRIPTION
**Pull request by andreybakanovsky**
! The background picture has to be professionally improved separately.

### CODE REVIEW

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
image

**Comment by andreybakanovsky** [comment]
Get back the white color of header by the previous commit like on the new design landing page [here](https://www.figma.com/file/F3DZs6zEHGkqkOuv3izTnR/Budgeting-kid-Client?type=design&node-id=1849-273&mode=dev).
Special instructions are required for different colors.
image

**Comment by andreybakanovsky** [comment]
Now we have the background. Should I put the dialog/forms in `.card.box` as on the screenshot:

image
image

**Review by ka8725 — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
