### PR TITLE
feat(header): update header with the avatar button

### PR DESCRIPTION
**Pull request by andreybakanovsky**

### CODE REVIEW

**Comment by andreybakanovsky** [comment]
image

**Review by VladislavSokov — APPROVED** [review]

**Comment by ka8725** [comment]
@andreybakanovsky please rebase it

**Comment by ka8725** [comment]
@andreybakanovsky as for me the dropdown doesn't pass the circled icon. Can we add some marker like "^", e.g.

image

**Comment by ka8725** [comment]
Also, let's fix margins in the logo (10px to the right) and below the header add 10px:

image

**Pull request merged**
